name: generate-images

on:
  pull_request:
    paths:
      - 'litclock.yaml'
  push:
    branches:
      - master
    paths:
      - 'litclock.yaml'
  workflow_dispatch:

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python dependencies
      run: pip install pyyaml

    - name: Run Python tests
      run: python -m unittest test_insert_quote test_yaml_to_formats -v

  generate-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Install Python dependencies
      run: pip install pyyaml

    - name: Generate JSON and CSV
      run: python yaml_to_formats.py

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: 'litclock.json litclock_annotated_improved.csv'
        commit_message: Update generated data files

  generate-images:
    runs-on: ubuntu-latest
    needs: [test-python, generate-data]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref || github.ref_name }}

    - name: Install Python dependencies
      run: pip install pyyaml "Pillow>=9.2"

    - name: Generate images
      run: |
        rm -rf images && \
        python quote_to_image.py

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: 'images/*'
        skip_dirty_check: true
        commit_message: Update images dir
