name: tests

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python dependencies
      run: pip install pyyaml

    - name: Run Python tests
      run: python -m unittest test_insert_quote test_yaml_to_formats -v

